### ISSUE TITLE
screencast: properly handle sessions

### ISSUE THREAD

**Issue by danshick** [emersion/xdg-desktop-portal-wlr#13]
At the moment, if you stop one screencast and attempt to start another without restarting xdg-desktop-portal-wlr, it will segfault.

Ideally, we should separate out a data structure that represents each output and its pipewire stream, as well as another data structure representing each d-bus screencast session. This would allow multiple sessions both in parallel or serially and would support parallel sessions reusing a pipewire node. If no sessions were using an output, we could destroy the output and recreate it as needed.

**Comment by emersion** [comment]
>Ideally, we should separate out a data structure that represents each output and its pipewire stream, as well as another data structure representing each d-bus screencast session.

I think as a first step just having a per-session struct would be enough. We can always improve it afterwards.

**Comment by danshick** [comment]
True. I just don't wanna start initiating duplicate screeencopy/pipewire loops for two sessions requesting the same output that could share a pipewire node. Still this would be an improvement for now to avoid restarting xdpw for consecutive sessions. Major thing I gotta figure out is properly destroying both pipewire and wlroots when we get session close.

**Comment by thotypous** [comment]
Workaround to use while this is not fixed correctly. This workaround does not support simultaneous sessions, but at least makes screen sharing work on Firefox, which opens one session for preview, closes it, then opens another one.
 
```diff
diff --git a/src/core/main.c b/src/core/main.c
index 40b0d20..1e8abe2 100644
--- a/src/core/main.c
+++ b/src/core/main.c
@@ -32,7 +32,7 @@ int xdpw_usage(FILE* stream, int rc) {
 	return rc;
 }
 
-int main(int argc, char *argv[]) {
+static int old_main(int argc, char *argv[]) {
 	const char* output_name = NULL;
 	const char* forced_pixelformat = NULL;
 	enum LOGLEVEL loglevel = ERROR;
@@ -176,3 +176,29 @@ error:
 	pw_loop_destroy(state.pw_loop);
 	return EXIT_FAILURE;
 }
+
+int main(int argc, char *argv[]) {
+	while (1) {
+		pid_t pid = fork();
+		if (pid == -1) {
+			perror("fork");
+			exit(EXIT_FAILURE);
+		}
+		if (pid == 0) {
+			_exit(old_main(argc, argv));
+		}
+		else {
+			int wstatus, w;
+			do {
+				w = waitpid(pid, &wstatus, 0);
+				if (w == -1) {
+					perror("waitpid");
+					exit(EXIT_FAILURE);
+				}
+			} while (!WIFEXITED(wstatus));
+			if (WEXITSTATUS(wstatus) != 123)
+				_exit(WEXITSTATUS(wstatus));
+		}
+	}
+	return EXIT_FAILURE;
+}
diff --git a/src/screencast/pipewire_screencast.c b/src/screencast/pipewire_screencast.c
index b288f79..7945279 100644
--- a/src/screencast/pipewire_screencast.c
+++ b/src/screencast/pipewire_screencast.c
@@ -80,6 +80,9 @@ static void pwr_handle_stream_state_changed(void *data,
 		pw_stream_state_as_string(state));
 	logprint(INFO, "pipewire: node id is %d", ctx->node_id);
 
+	if (ctx->stream_state && state == PW_STREAM_STATE_PAUSED)
+		exit(123);
+
 	switch (state) {
 	case PW_STREAM_STATE_STREAMING:
 		ctx->stream_state = true;
```

**Comment by nostdm** [comment]
I haven't delved into the code to debug lower level issues but so far playing around with chromium I found out the following:

**Chromium:** Version 83.0.4100.3 (Official Build) Arch Linux (64-bit)
**Compositor:** sway version 1.4-fcd524bb (Mar 21 2020, branch 'master')

- By default the browser crashes when sharing the screen.
- When I enable pipewire in chrome://flags it doesn't crash and shows the screen sharing popup.
- I start the xdg-desktop-portal with `/usr/lib/xdg-desktop-portal -r`.
- Because the first connection is usually a segfault I start the xdg-desktop-portal-wlr with `while true; do xdg-desktop-portal-wlr -p BGRx; done` to make it restart automatically as it crashes.
- When presenting in meet.google.com I can see a proper thumbnail which actually shows my screen, but when I actually share it, the screen capture becomes frozen after a few seconds and shows only a static image.
- When I use a service like https://www.webrtc-experiment.com/Pluginfree-Screen-Sharing to test the screen sharing, I don't see a thumbnail (only a white box) but interestingly when I actually share the screen the screen capture doesn't become frozen like with meet.google.com.
- As per missing session handling, when I close the screen sharing tab in the browser, or even close the browser entirely, the xdg-desktop-portal-wlr process is still doing the processing and using a lot of CPU. Hence I need to `Ctrl-c` if I want to stop it.

I hope this is useful debug information - I'll try to go a bit more in depth if I find a bit of spare time this week.

**Comment by danshick** [comment]
This is helpful in understanding Chrome's behavior. After the next PR for session support, it would be good to confirm if these behaviors are improved.

**Comment by danshick** [comment]
Anyone wanting to test out the WIP branch in the referenced PR is encouraged to do so.
