### ISSUE TITLE
Would it make sense to intercept org.freedesktop.portal.Settings portal interface of  xdg-desktop-portal?

### ISSUE THREAD

**Issue by jnpkrn** [emersion/xdg-desktop-portal-wlr#40]
Sorry, I am a bit lost in how these portals work, but what I know, there is
a problem with sway vs. `bwrap`ped (Flatpak, WebKitGTK self-imposed
sandboxing) applications with `GDK_BACKEND=wayland` unless `xsettings`
GSettings schema files from gnome-settings-damon are installed (together
with `xdg-desktop-portal{,-gtk}`):

https://github.com/flatpak/flatpak/issues/2861
https://bugs.webkit.org/show_bug.cgi?id=213148

Just wanted to start a discussion whether `wlroots` backend is not the right
component to respond to queries like "what kind of aliasing does the screen
uses", so that users of `wlroots` backed window managers/compositors
don't need to:

* fiddle with `gsettings`/`gnome-settings-daemon`

  - `wlroots` component already has [its own entry point](https://github.com/swaywm/wlroots/pull/1533) for
    a user override (as, e.g., configurable in `sway` config)

* suffer from incorrect antialising being chosen without an explicit override
   through components above (currently, GTK3 defaults to `none` which is
   painful on its own, but I can see that even if it gets [fixed](https://github.com/flatpak/flatpak/issues/2861#issuecomment-643694968), it may still
   be wrong with respect to the display at hand)

Beside mere interception of the queries like:

```
gdbus call --session --dest org.freedesktop.portal.Desktop --object-path /org/freedesktop/portal/desktop --method org.freedesktop.portal.Settings.ReadAll \[\"org.gnome.settings-daemon.plugins.xsettings\"\]
```

would it make sense to attempt at unification around what's being queried
through `xsettings` by the `xdg-desktop-portal` these days?  Something that
would reflect on the particular screen the querying application is running at,
perhaps?

I put some more thoughts at [related issue bug](https://bugzilla.redhat.com/show_bug.cgi?id=1845743#c24) it these are worthy
at all (note: at the very beginning of the learning curve, would prefer
if things just worked, indeed :-) ).

**Comment by danshick** [comment]
I'll start by saying that I don't think any active contributors to xdpw use flatpak, nor have a desire to support it. That's not to say PRs wouldn't be accepted, just that it would likely require someone new to come along and contribute the needed code.

That said, it looks like the fallback behavior is working correctly, and that what is actually missing are appropriate schemas installed by gnome-settings-daemon (per the issue you linked). I, personally, don't want to replace any portals that are working correctly with our implementations. It would be better to correct distro packaging to add optional or require dependencies where appropriate in order to make this "just work". Maybe the needed schemas could be packaged separately from the daemon?

If this were to be built, to report settings for which the compositor is the single source of truth, it might eat other valid responses that should come from a fallback implementation. What settings are supported and where the values of those settings are sourced is entirely open ended. The portal document itself even says that what is and isn't a valid key is an undocumented implementation detail [here](https://github.com/flatpak/xdg-desktop-portal/blob/master/data/org.freedesktop.impl.portal.Settings.xml#L26).

**Comment by danshick** [comment]
From further reading through the issue comments, it looks like KDE's implementation somehow fixes this bug even though it is only reporting KDE specific settings in a KDE specific namespace?? I'm not sure how that works. Is there positive confirmation anywhere that KDE doesn't have antialiasing issues in GTK flatpak apps without the appropriate schemas installed for gsettings/dconf via a package similar to gnome-settings-daemon?

Also, per the discussion in the RH bug tracker, I wholeheartedly disagree with the assessment that the package shouldn't/won't be split, or that gnome-settings-daemon or a resulting split-off portion shouldn't be made (at least) an optional dependency of flatpak or xdp.

**Comment by danshick** [comment]
After further discussing it with @emersion and @kennylevinsen, I don't think this would be an appropriate feature for xdpw. DPI and subpixel information is available via wayland, and it seems that whatever settings are needed from the fallback portal work appropriately with the correct schemas installed.

**Comment by mcatanzaro** [comment]
> Also, per the discussion in the RH bug tracker, I wholeheartedly disagree with the assessment that the package shouldn't/won't be split, or that gnome-settings-daemon or a resulting split-off portion shouldn't be made (at least) an optional dependency of flatpak or xdp.

There's no reason to make flatpak depend on gnome-settings-daemon. We will just move the settings, https://gitlab.gnome.org/GNOME/gsettings-desktop-schemas/-/issues/31. That should solve this nicely for everyone not using GNOME, whereas a downstream solution would only help Fedora users.

**Comment by danshick** [comment]
Makes sense. Thanks.
