### ISSUE TITLE
Arch Linux package in community

### ISSUE THREAD

**Issue by shibumi** [emersion/xdg-desktop-portal-wlr#56]
Hi,
is this still being worked on? If so, can you schedule a new release?
I would like to package this for the official Arch Linux repositories :)

**Comment by danshick** [comment]
This is still being actively developed, but I think any tagged release would be appropriate for inclusion from a stability point of view.

**Comment by danshick** [comment]
Reread your issue. I expect output selection to be done in October. That would be the next minor version bump I suspect. I think HEAD is currently stable enough for a bugfix bump. Is 0.1.0 not able to be included in extra?

**Comment by shibumi** [comment]
0.1.0 would be enough to be included, but I had problems  making it running. So I thought this may be fixed in a late version.

**Comment by danshick** [comment]
I think the issue I've seen the most people tripped up by is systemd not being aware of the XDG_CURRENT_DESKTOP variable, and most people end up needing to run something like `exec systemctl --user import-environment` from their sway config.

This is documented here in the GitHub Wiki (maybe not well enough), but isn't available to an end user installing from a package management tool. There are no man pages and little opportunity to see the help text because it is hopefully autostarted by d-bus.

If you experienced different issues, I'd like to troubleshoot them (or document them) so that we can create something more stable for everyone prior to packaging.

**Comment by shibumi** [comment]
Ok,

here is what I did. I have the following lines in my `.zshrc` file that starts sway:
```
export XDG_CURRENT_DESKTOP=sway
export XDG_SESSION_TYPE=wayland
# Exec sway
if [ "$(tty)" = "/dev/tty1" ]; then
  exec sway
fi
```

This works so far and when I do `echo $XDG_CURRENT_DESKTOP` i get the right value back. I have also enabled the WebRTC Pipewire flag in my chromium: `#enable-webrtc-pipewire-capturer` on Arch Linux.

Furthermore I have installed the Arch Linux packages `libpipewire02` and `pipewire`.

I am testing with meet.google.com and when I try to share a screen I just see a black window. What am I doing wrong?

**Comment by sentriz** [comment]
Try put the env vars in `~/.config/environment.d/envvars.conf` instead

On 27 September 2020 14:51:06 IST, Christian Rebischke <notifications@github.com> wrote:
>Ok,
>
>here is what I did. I have the following lines in my `.zshrc` file that starts sway:
>```
>export XDG_CURRENT_DESKTOP=sway
>export XDG_SESSION_TYPE=wayland
># Exec sway
>if [ "$(tty)" = "/dev/tty1" ]; then
>  exec sway
>fi
>```
>
>This works so far and when I do `echo $XDG_CURRENT_DESKTOP` i get the right value back. I have also enabled the WebRTC Pipewire flag in my chromium: `#enable-webrtc-pipewire-capturer` on Arch Linux.
>
>Furthermore I have installed the Arch Linux packages `libpipewire02` and `pipewire`.
>
>I am testing with meet.google.com and when I try to share a screen I just see a black window. What am I doing wrong?
>
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/emersion/xdg-desktop-portal-wlr/issues/56#issuecomment-699638255
-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by shibumi** [comment]
@sentriz when I do the variables in `~/.config/environment.d/envvars.conf` the variables will not get loaded. Do you have any idea why?

**Comment by shibumi** [comment]
@sentriz ok.. I have the variables in both now. In the `.zshrc.local` files and `~/.config/environment.d/envvars.conf` this seems to work. However I can only share one of my two displays?! oO

**Comment by shibumi** [comment]
Whatever.. this proves for me, that the software is working. I will prepare everything and push this project to the community repository :)

**Comment by danshick** [comment]
@shibumi Environment variables are always inherited from the parent process. Your sway session is inheriting them from your zsh script and therefore any program launched by sway, including terminals can see that variable. xdpw is launched via d-bus activation as a user service. systemd's user service starts independently of sway and therefore cannot see those envvars. Putting them in your ~/.config/... folder is a systemd specific way of defining your environment, but as your systemd user session is not starting sway, it can't see them when set in there. They are mutually exclusive.

As for selecting which screen to share, that feature is being worked on at the moment. There's a CLI flag that can be used for now, but it is cumbersome.

**Comment by danshick** [comment]
I'm gonna close this issue, but I will take the feedback that the documentation needs to be improved around environment variables. We might also want to ship a man page in the future. Something to think about.

**Comment by shibumi** [comment]
> There's a CLI flag that can be used for now, but it is cumbersome.

Is this documented somwehre, @danshick ?

**Comment by danshick** [comment]
> > There's a CLI flag that can be used for now, but it is cumbersome.
> 
> Is this documented somwehre, @danshick ?

Instructions on running xdpw with flags:

https://github.com/emersion/xdg-desktop-portal-wlr/wiki/FAQ#but-i-need-to-use-a-cli-flag-why-cant-i-just-run-xdpw-directly

The available flags are in the help text, but you're looking for `-o OUTPUT_NAME`. Make sure this flag is applied to xdpw and not xdp. Make sure xdg-desktop-portal-wlr is killed first.

**Comment by soyuka** [comment]
Would it be possible to keep this issue open and close it when the package is available? @shibumi when you add the package, note that there are some confusions about what is needed for this to work (as it's dependent of xdg-desktop-portal and doesn't replace xdg-desktop-portal-kde. However it's sufficient to use screen sharing on sway see https://aur.archlinux.org/packages/xdg-desktop-portal-wlr-git/ for a discussion around this).

**Comment by danshick** [comment]
@soyuka This issue isn't really an xdpw issue at all as it is distro specific, so I don't think it is appropriate to reopen it.

That being said, inclusion in any Arch repository (in this case, community) will solve the issues you've had about xdg-desktop-portal requiring some other portal implementation. The difficulty with the AUR is that xdp is a dependency of xdpw that needs to be installed before xdpw is built by makepkg, but xdpw is not built yet, so xdp(k,g) needs to be used temporarily until xdpw is built and satisfies this dependency. Once the package is in community, this problem goes away, because there is no makepkg step required for regular users.

In fact, even AUR users will have the option to install the -wlr package available in community to satisfy the makepkg dependency issue, which would then be overwritten once the AUR package is built and pacman attempts to install it.

This is a confusing quirk of pacman/makepkg, but one which we should hopefully have to think about less once there is a non-AUR -wlr option.

**Comment by shibumi** [comment]
@soyuka @danshick package is in community now: https://www.archlinux.org/packages/community/x86_64/xdg-desktop-portal-wlr/

Ping me when something is odd.
